### PR TITLE
Rebase timberlandmaster_final onto upstream

### PR DESCRIPTION
**Pull request by mwilck**
We need to rebase the timberlandmaster_final branch onto dracutdevs/master in order to have it merged in https://github.com/dracutdevs/dracut/pull/2184.

I saved the current code as [timberland_059](https://github.com/timberland-sig/dracut/tree/timberland_059).

### CODE REVIEW

**Review by johnmeneghini — COMMENTED** [review]
I don't understand the purpose of this pull request.  What are you trying to do?  I had previously rebased timberland_final onto the upstream tag 059.  This pull request is trying to merger what's upstream into timberland_final.

**Comment by johnmeneghini** [comment]
Here's what my repository looks like.  This is the repository I used to create the timberland sig public dracut repo.

```
jmeneghi:dracut(timberlandmaster-059-final) > git logl -10
28df87d1 2023-01-12 1673517995  (HEAD -> timberlandmaster-059-final, private/timberlandmaster-059-final, origin/timberland_final) fix(iscsi): install 8021q module unconditionally [ Martin Wilck / mwilck@suse.com ]
eddf48b3 2023-01-12 1673517995  fix(nvmf): install 8021q module unconditionally [ Martin Wilck / mwilck@suse.com ]
0f68b5e9 2023-01-12 1663844754  feat(nvmf): enable module if NBFT exists [ Martin Wilck / mwilck@suse.com ]
b8b8b087 2023-01-12 1660836441  feat(nvmf): add NBFT connect support, and fix configuration priority [ Martin Wilck / charles.rose@dell.com ]
870e3933 2023-01-12 1663357012  feat(nvmf): add code for parsing the NBFT [ Martin Wilck / mwilck@suse.com ]
0aa08f0e 2022-12-24 1671900567  (tag: 059, private/master-059, origin/timberland-059, timberland-059) docs: update NEWS.md and AUTHORS [ Jóhann B. Guðmundsson / johannbg@gmail.com ]
794ce5e3 2022-12-24 1671897185  fix(NEWS.md): add missing entries [ Jóhann B. Guðmundsson / johannbg@gmail.com ]
b3d219b4 2022-12-24 1671718789  fix(systemd-timedated): add missing dbus-org.freedesktop.timedate1.service [ Jóhann B. Guðmundsson / antonio.feijoo@suse.com ]
4fca292b 2022-12-24 1671718409  fix(systemd-hostnamed): add missing dbus-org.freedesktop.hostname1.service [ Jóhann B. Guðmundsson / antonio.feijoo@suse.com ]
7ed04618 2022-12-24 1671708870  fix(dbus-broker): add missing sockets.target.wants/dbus.socket [ Jóhann B. Guðmundsson / antonio.feijoo@suse.com ]
```

**Comment by johnmeneghini** [comment]
```
jmeneghi:dracut(timberlandmaster-059-final) > git remote -v
origin  https://github.com/timberland-sig/dracut.git (fetch)
origin  https://github.com/timberland-sig/dracut.git (push)
private https://github.com/timberland-sig/dracut-private.git (fetch)
private https://github.com/timberland-sig/dracut-private.git (push)
upstream        https://github.com/dracutdevs/dracut.git (fetch)
upstream        https://github.com/dracutdevs/dracut.git (push)
```

**Comment by johnmeneghini** [comment]
I did a fetch and looked at this and I don't understand what you're doing with this branch. I think this this branch is junk. If you you want to rename the default/feature branch in this repository from timberland-59 to timberlandmaster_final, there better ways to do this.  Maybe we should clean up some of the extra branches we have lying around.  They are confusing.

```
jmeneghi:dracut(timberland-059) > git fetch origin 
remote: Enumerating objects: 84, done.
remote: Counting objects: 100% (61/61), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 84 (delta 56), reused 61 (delta 56), pack-reused 23
Unpacking objects: 100% (84/84), 19.94 KiB | 785.00 KiB/s, done.
From https://github.com/timberland-sig/dracut
 * [new branch]        timberland_059                 -> origin/timberland_059
 + 28df87d1...26c0fabb timberland_final               -> origin/timberland_final  (forced update)
 * [new branch]        timberland_pr_v1               -> origin/timberland_pr_v1
 * [new branch]        timberland_pr_v2               -> origin/timberland_pr_v2
 * [new branch]        timberlandmaster_final_rebased -> origin/timberlandmaster_final_rebased
```

**Comment by mwilck** [comment]
> I think this this branch is junk.

The branch is not junk. `timberlandmaster_final_rebased` is my set of patches based on the current dracut master branch (a6dd5bf). It's the same code that you have in https://github.com/johnmeneghini/dracut/pull/1, except for one additional upstream patch (61ceb35), which apparently went in upstream after I did the rebase.

What I want to do is bring this code base to `timberland_final`, because that's the branch I (perhaps mistakenly??) used to create the upstream PR. Upstream has explicitly [asked me](https://github.com/dracutdevs/dracut/pull/2184#pullrequestreview-1296279038)  to rebase the PR.

Perhaps this PR against `timberland_master` is junk; I just did it to show you and the other members of the Timberland group what I was about to do. Apparently a bad idea; it's creating more confusion than anything. Note that dracut upstream never merges, for whatever reason they just rebase. Therefore we can't actually "merge" this either. I'll have to force-push it to `timberland_master. I just wanted to make this explicit.

> Maybe we should clean up some of the extra branches we have lying around. They are confusing.

 * `timberland_final`: the branch for the PR, to be rebased
 * `timberland_059`: timberland changes based on `059`, currently identical to `timberland_final`
 * `timberland_pr_v1`, `timberland_pr_v2`: previous versions of the PR; for reference
 * `timberlandmaster_final_rebased`: this branch, to be deleted after `timberland_final` is updated.

We can shred the previous versions if nobody cares about them.

**Comment by charles-rose** [comment]
@mwilck,

After review and testing, I see this error reported when the system boots up:
NBFT: jq error while processing ".host_name"

Because .host_name is not present on this system:
    "hfi":[
      {
        "index":1,
        "transport":"tcp",
        "pcidev":"0:1:0.0",
        "mac_addr":"ec:2a:72:33:06:cc",
        "vlan":0,
        "ip_origin":82,
        "ipaddr":"100.68.144.67",
        "subnet_mask_prefix":24,
        "gateway_ipaddr":"100.68.144.254",
        "route_metric":500,
        "primary_dns_ipaddr":"100.64.0.111",
        "secondary_dns_ipaddr":"10.228.254.66",
        "dhcp_server_ipaddr":"100.64.0.11",
        "this_hfi_is_default_route":1,
        "dhcp_override":1
      }

This is a benign message. Empty IP addresses are checked with nbft_check_empty_address, something similar for strings would be nice.

**Comment by mwilck** [comment]
> @mwilck,
> 
> After review and testing, I see this error reported when the system boots up: NBFT: jq error while processing ".host_name"

Right. Feel free to open an issue for that.

**Comment by mwilck** [comment]
I am closing this now. As @johnmeneghini pointed out, it's causing more confusion than it's doing good.

However, I think we should move forward with `timberland_final` for now. The name isn't well chosen, but that ship has sailed; the upstream discussion is on https://github.com/dracutdevs/dracut/pull/2184, which I made from that branch.

**I will update `timberland_final` by force-pushing soon.**

**Pull request closed without merging**
