### PR TITLE
Timberland final

### PR DESCRIPTION
**Pull request by johnmeneghini**
feat(nvmf): add code for parsing the NBFT
    
Add code to parse the NvmeoF Boot Firmware Table (NBFT).
The table is read by nvme-cli and printed in json format.
The jq utility is used for parsing the json output.

Set rd.neednet if valid nbft entries found; this is possible
because this script runs before 98-parse-ip-options.sh

Also add has_ibft_config markers for NBFT interfaces. We can use
"ibft" for this. Otherwise we'd have to modify the networking
tools. For the logic this is used for, all that matters is that
this is an external configuration mechanism applied during boot.

Usage of DHCP (either for obtaining initiator parameters and possibly
root-path) is indicated in "nvme show-nbft" output by a non-empty value
for dhcp_server_ipaddr in the HFI record.

## Checklist
- [x ] I have tested it locally
- [x ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

### CODE REVIEW

**Comment by mwilck** [comment]
@johnmeneghini, could you please add @aafeijoo-suse to the list of reviewers?

**Review by mwilck — APPROVED** [review]

**Comment by igaw** [comment]
Don't have alot of experience with the dracut code base but it looks reasonable from my point of view.

**Review by igaw — APPROVED** [review]

**Comment by mwilck** [comment]
@johnmeneghini, I have no write access to this repostitory. Could you please grant it to me?

**Comment by mwilck** [comment]
I believe this PR is mostly outdated and should be deleted.
There's confusion about the branch naming (probably my fault).

Shouldn't our actual "master" branch (from which we do the upstream PR) be `timberland_final`? 
We can have additonal branches based on upstream releases, e.g. `timberland_059` etc. But we should make sure we use a common nomenclature. In general the timberland project seems to prefer the underscore over the dash. So I propose `timberland_059`.

**Comment by johnmeneghini** [comment]
> Shouldn't our actual "master" branch (from which we do the upstream PR) be `timberland_final`? We can have additonal branches based on upstream releases, e.g. `timberland_059` etc. But we should make sure we use a common nomenclature. In general the timberland project seems to prefer the underscore over the dash. So I propose `timberland_059`.

That's up to you.  Since you're the maintainer of this repository you can setup the default branch to be anything you'd like.

**Comment by Douglas-Farley** [comment]
As John says, that's up to you @mwilck - but I would vote for `timberland_final` or `timberland_1.0` rather than `*_059` which is a reference to a pre-published spec revision (that wasn't even the final one!).

**Comment by johnmeneghini** [comment]
> As John says, that's up to you @mwilck - but I would vote for `timberland_final` or `timberland_1.0` rather than `*_059` which is a reference to a pre-published spec revision (that wasn't even the final one!).

This is the `timberland_final` branch and it's the working branch that was used to push this work upstream.  So we can't really use timberland_final for a default/feature branch name here in timberland sig.  Since many of the changes on this branch are being cherry-picked and merged upstream I think we need to remove those shas from this branch.  Other than that, I think this branch should be fine.   It needs to be rebased onto the master branch after clean up.

**Comment by johnmeneghini** [comment]
I've rebased and refactored this branch as suggested above in my private repo.  Please see 

https://github.com/johnmeneghini/dracut/pull/1

to see what it looks like.

**Comment by mwilck** [comment]
> *_059 which is a reference to a pre-published spec revision

I thought it was a reference to **dracut** 059.

**Comment by mwilck** [comment]
> I've rebased and refactored this branch as suggested above in my private repo. Please see
> 
> [johnmeneghini#1](https://github.com/johnmeneghini/dracut/pull/1)
> 
> to see what it looks like.

The code you created is almost the same as mine in #3. I tried to explain my thinking in https://github.com/timberland-sig/dracut/pull/3#issuecomment-1430298417.

**Comment by mwilck** [comment]
I believe we want close this PR. The timberland-059 branch is outdated.

**Comment by mwilck** [comment]
@johnmeneghini do you agree with closing this PR? If yes, please do.

**Comment by johnmeneghini** [comment]
Closing this PR. Please use the the upstream pull request for further work and review.  Not that pushing patches to this branch, `timberland_final`, will result in updating the upstream pull request. 

https://github.com/dracutdevs/dracut/pull/2184

**Pull request closed without merging**
